modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/VazkiiMods/Zeta"
license = "https://github.com/VazkiiMods/Zeta/blob/master/LICENSE.md"


[[mods]]
modId = "zeta"
version = "${version}"
displayName = "Zeta"
displayURL = "https://violetmoon.org"
authors = "Vazkii, quat, IThundxr, Siuolplex, wiresegal, MehVahdJukaar" #optional
description = '''A fully featured Library designed around loading highly configurable, agile developed. modular mods'''

[[dependencies.zeta]]
   modId = "forge"
   mandatory = true
   versionRange = "[${forge_version},)"
   ordering = "NONE"
   side = "BOTH"


[[dependencies.zeta]]
   modId = "minecraft"
   mandatory = true
   versionRange = "${minecraft_version}"
   ordering = "NONE"
   side = "BOTH"
