modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/VazkiiMods/Zeta"
license="https://github.com/Vazkii/VazkiiMods-/blob/master/LICENSE.md"

[[mods]]
modId="zeta"
displayName="Zeta"
version="${mod_version}"
authors="Vazkii, quat, iThundxr, siuol, wiresegal, MehVahdJukaar"
description='''A fully featured Library designed around loading highly configurable, agile developed. modular mods'''

[[dependencies.zeta]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.zeta]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
